
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "REGEX RETURN STRINGregra : REGEX RETURN '(' conteudo ')'conteudo : conteudo : elementoselementos : STRINGelementos : conteudo ',' STRING"
    
_lr_action_items = {'REGEX':([0,],[2,]),'$end':([1,8,],[0,-1,]),'RETURN':([2,],[3,]),'(':([3,],[4,]),')':([4,5,6,7,10,],[-2,8,-3,-4,-5,]),',':([4,5,6,7,10,],[-2,9,-3,-4,-5,]),'STRING':([4,9,],[7,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'regra':([0,],[1,]),'conteudo':([4,],[5,]),'elementos':([4,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> regra","S'",1,None,None,None),
  ('regra -> REGEX RETURN ( conteudo )','regra',5,'p_regra','teste.py',30),
  ('conteudo -> <empty>','conteudo',0,'p_conteudo_vazio','teste.py',33),
  ('conteudo -> elementos','conteudo',1,'p_conteudo_elementos','teste.py',36),
  ('elementos -> STRING','elementos',1,'p_elementos_elem','teste.py',39),
  ('elementos -> conteudo , STRING','elementos',3,'p_elementos_varios','teste.py',42),
]
